# arb-dir: lib/l10n
# template-arb-file: app_en.arb
# untranslated-messages-file: l10n_errors.txt
# output-dir: lib/l10n/generated

# To make use of Authenticator enums
header: import 'package:amplify_authenticator/amplify_authenticator.dart';
arb-dir: lib/l10n/src/amplify
output-localization-file: amplify_localizations.dart
template-arb-file: amplify_en.arb
untranslated-messages-file: l10n_amplify_errors.txt
output-dir: lib/l10n/generated
output-class: AuthenticatorLocalizations

nullable-getter: false
synthetic-package: false